# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([23,46,86,78,36])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(a)
a.sort()


[23 46 86 78 36]


# Problem 2

In [22]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
m = np.array([10,15,30,60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
n = np.arange(5,15,1)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
k = np.arange(50,100,5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
ç = np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
d = np.random.randint(10,30,5)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
x = np.linspace(-1,1,10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
m = np.random.randint(10,50, size=(3,5))
print(m)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayını ?
a = np.sum(m,axis =1)
b = np.sum(m,axis=0)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
enBüyük = np.max(m)
enKücük = np.min(m)
ortalama = (enBüyük + enKücük ) / 2
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
indeks = np.unravel_index(np.argmax(m),m.shape)
print(indeks)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
n = np.linspace(10,20,num=11)
v = n[:3]

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
dizi = np.linspace(10,20,num=11)
ters = dizi[::-1]

# 15- Üretilen matrisin ilk satırını seçiniz.
m = np.random.randint(10,50, size=(3,5))
k = m[0:1]
print(k)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

m = np.random.randint(10,50, size=(3,5))
k = m[1:2]
print(k)
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
m = np.random.randint(10,50, size=(3,5))
k = m[:,0]

# 18- Üretilen matrisin her bir elemanının karesini alınız.

m = np.random.randint(10,50, size=(3,5))
k = np.square(m)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
m = np.arange(-50,50)
for i in m:
    if i > 0:
        if i % 2 == 0:
            print(i)
       



[[23 37 40 48 46]
 [35 38 30 37 35]
 [13 22 12 32 45]]
(0, 3)
[[16 47 15 33 43]]
[[31 32 33 14 26]]
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
