# Problem 1

In [17]:
# 1 - numpy kütüphanesini import edin 
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.arange(0,10,2)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
np.resize(a,(3,5))
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)


[0 2 4 6 8]
(5,)
1


# Problem 2

In [40]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
m = np.arange(1,10,2)
print(m)
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(m,[3]))

# 3 - Parçalanmış matrisleri birleştirin
m = np.arange(1,10,2)
n = np.arange(11,20,2)
print(np.concatenate([m,n]))

[1 3 5 7 9]
[array([1, 3, 5]), array([7, 9])]
[ 1  3  5  7  9 11 13 15 17 19]


# Problem 3

In [64]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin
