# Numpy
- Numpy sayılsal işlemleri hızlı yapmak için.
- Veri analizinde kullanılır.
- Bilimsel hesaplamalar için kullanılır
- Listelere benzerdir fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

In [1]:
#KLASİK YÖNTEM
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)
    

[2, 6, 12, 20]


In [2]:
# yeni yöntem
import numpy as np 
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)


[ 2  6 12 20]


In [2]:
# .reshape() fonskiyonun ile arraylerin boyutlarını degistirir.
import numpy as np 
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#shape ile arrayin boyutunu verir.
print(multi.shape)
x.shape

(3, 3)


(9,)

In [7]:
# .ndim arraylerin boyut sayısı öğrenilir
print(x.ndim)
print(multi.ndim)

1
2


## BİRLEŞTİRME (CONCATENTİON)

In [9]:
# .concatention() fonksiyonu ile birleştirme yapabiliriz.
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [15]:
a = np.array([[1,2,3],[4,5,6,]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [17]:
a = np.array([[1,2,3],[4,5,6,]])
print(np.concatenate([a,a],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Array Ayırma (Splitting)

In [19]:
m = np.array([1,2,3,100,101,55,56,57])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([100, 101]), array([55, 56, 57])]


In [20]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[100 101]
[55 56 57]


In [22]:
n = np.arange(16).reshape(4,4)


np.hsplit(n,[2]) ## DİKEY AYIRIR



[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
np.vsplit(n,[2]) ## YATAY AYIRIR

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### np.arange()
- belirli bir aralıkta sayıları gruplamak icin kullanılır.
- np.arange(start,stop,step)

In [24]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [26]:
np.zeros(5) ## 5 tane sıfır

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(5) ## 5 tane bir

array([1., 1., 1., 1., 1.])

In [29]:
np.linspace(0,50,6) # Aralığa böler             

array([ 0., 10., 20., 30., 40., 50.])

In [30]:
np.random.randint(0,100,5) ## 0 ile 100 arasında random 5 sayı üret

array([33,  1,  3, 93, 39])

In [31]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


## Numpy Array'in Özellikleri
 - ndim : Boyut sayısı
 - shape: Boyut bilgisi
 - size : Toplam Eleman sayısı
 - dtype: Veri tipi

In [32]:
a = np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int64


## Array Sıralama(Sorting)
- Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [33]:
v = np.array([10,30,15,54,35,83,67,23,63])
print(v)
v.sort()

[10 30 15 54 35 83 67 23 63]


In [41]:
a = np.random.normal(20,5,(3,3))
print(a)

[[19.11530839 19.55284518 17.85014875]
 [22.85133573 19.18698603 15.44379103]
 [26.09482344 31.14774007 23.08199325]]


In [43]:
print(np.sort(a,axis=0))

[[19.11530839 19.18698603 15.44379103]
 [22.85133573 19.55284518 17.85014875]
 [26.09482344 31.14774007 23.08199325]]


In [44]:
print(np.sort(a,axis=1))

[[17.85014875 19.11530839 19.55284518]
 [15.44379103 19.18698603 22.85133573]
 [23.08199325 26.09482344 31.14774007]]
